---
- name: Install redis
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - redis32u
    - python36u-redis

- name: Make sure redis is started at boot.
  service:
    name: redis
    enabled: true
    state: started
