---
- name: Install PostgreSQL YUM repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/testing/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm
    state: present

- name: Install PostgreSQL 10 Server
  yum:
    name: postgresql10-server
    state: present

- name: Install PostgreSQL 10 devel package
  yum:
    name: postgresql10-devel
    state: present

- name: Install PostgreSQL 10 contrib package
  yum:
    name: postgresql10-contrib
    state: present

- name: Initialize PostgreSQL 10
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb creates=/var/lib/pgsql/10/initdb.log
  become: true
  become_user: root

- name: Create a symbolic link to pg_config binary so pip installs of psycopg2 work
  file:
    src: /usr/pgsql-10/bin/pg_config
    dest: /usr/bin/pg_config
    state: link

- name: Allow connections from localhost IPv4 user accounts via psycopg2 (no scram-sha-256 yet)
  lineinfile:
    path: /var/lib/pgsql/10/data/pg_hba.conf
    insertafter: '# IPv4 local connections:'
    line: 'host    all             all             127.0.0.1/32            md5'

- name: Allow connections from localhost IPv6 user accounts via psycopg2 (no scram-sha-256 yet)
  lineinfile:
    path: /var/lib/pgsql/10/data/pg_hba.conf
    insertafter: '# IPv6 local connections:'
    line: 'host    all             all             ::1/128                 md5'

- name: Ensure PostgreSQL 10 service is running
  service:
    name: postgresql-10
    state: restarted
    enabled: yes

- name: Ensure psycopg2 is installed
  yum:
    name: python-psycopg2
    state: present
