---
- name: Install mod_php 7.1 for Apache httpd from IUS
  yum:
    name: 
      - mod_php71u
      - php71u-mysqlnd
    state: present

- name: place mod_wsgi config
  copy:
    src: "mod_php-7.1.conf"
    dest: "{{ httpd_ext_dir }}/10-mod_php-7.1.conf"
    owner: root
    group: root
    mode: 0644
