---
- name: Install mod_php 7.2 for Apache httpd from IUS
  yum:
    name: 'mod_php72u'
    state: present

- name: place mod_wsgi config
  copy:
    src: "mod_wsgi-python3.6.conf"
    dest: "{{ httpd_ext_dir }}/10-wsgi-python3.6.conf"
    owner: root
    group: root
    mode: 0644
