---
- name: Install mod_wsgi for Apache httpd with Python from IUS
  yum:
    name: 'python36u-mod_wsgi'
    state: present

- name: Make sure httpd is started at boot.
  service:
    name: httpd
    enabled: true
    state: restarted
