---
- name: Install Python from IUS
  yum:
    name: ['python36u', 'python36u-pip', 'python36u-devel']
    state: present

- name: Create symlink for Python 3.
  become: yes
  file:
    src: '/usr/bin/python3.6'
    dest: '/usr/bin/python3'
    state: link

- name: Create symlink for pip 3.
  become: yes
  file:
    src: '/usr/bin/pip3.6'
    dest: '/usr/bin/pip3'
    state: link
