---
- name: Create django directories
  file:
    name: "/var/django/{{ item }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  with_items:
    - sites
    - media
    - logs
