---
- name: Create django directories
  file:
    name: "/var/django/{{ item }}"
    state: directory
    owner: django_deploy
    group: apache
    mode: 0775
  with_items:
    - sites
    - media
    - logs
