---
- name: Install PostgreSQL YUM repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/testing/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm
    state: present

- name: Install PostgreSQL 10 devel package
  yum:
    name: postgresql10-devel
    state: present

- name: Create a symbolic link to pg_config binary so pip installs of psycopg2 work
  file:
    src: /usr/pgsql-10/bin/pg_config
    dest: /usr/bin/pg_config
    state: link

- name: Ensure psycopg2 is installed
  yum:
    name: python-psycopg2
    state: present
