---
- import_playbook: web-common.yml host_group=web-py WEB_ENVIRONMENT="prod"
- name: Additional tasks to be performed on the prod servers
  hosts: py-web-prod
  become: yes
  vars:
    # WEB_ENVIRONMENT: either `prod` or `nonprod` for cert naming convention
    "WEB_ENVIRONMENT": "prod"

    # DEFAULTS for the template, if not overridden in `sites`
    "USER": "apache"
    "GROUP": "apache"
    "DJANGO_ROOT": "/var/django/sites"
    "VIRTUALENV_ROOT": "/var/django/virtualenvs"
    "STATIC": true

    # Websites / domains for these servers to host
    "websites": [
        {
            "name": "wrds-api-prod",
            "server_name": "wrds-api.wharton.upenn.edu",
            "sites": [
                {
                    "path": "/",
                    "django_root": "/var/django/wrdsapi/sites",
                    "virtualenv_root": "/var/django/wrdsapi/virtalenvs",
                    "project": "wrds-api-prod",
                    "user": "wrdsapi",
                    "group": "wharton"
                }
            ]
        },
        {
            "name": "wrds-classroom-prod",
            "server_name": "wrds-classroom.wharton.upenn.edu",
            "sites": [
                {
                    "path": "/llbacktester",
                    "project": "ll-backtester-project-prod"
                },
                {
                    "path": "/otis",
                    "project": "otis-prod"
                },
                {
                    "path": "/",
                    "project": "classroom-prod",
                    "static": false
                }
            ]
        },
        {
            "name": "wrds-www-prod",
            "server_name": "wrds-www.wharton.upenn.edu",
            "sites": [
                {
                    "path": "/",
                    "project": "django-wrds-prod",
                    "media_path": "/var/media/wrds-www"
                }
            ]
        }
    ]
  roles:
    - { role: "web_all_apache_conf", tags: ['web'] }
