---
- import_playbook: web-common.yml host_group=web-py WEB_ENVIRONMENT="prod"
- name: Additional tasks to be performed on the prod servers
  hosts: web-py
  become: yes
  vars:
    # WEB_ENVIRONMENT: either `prod` or `nonprod` for cert naming convention
    "WEB_ENVIRONMENT": "prod"

    # DEFAULTS for the template, if not overridden in `sites`
    "USER": "apache"
    "GROUP": "apache"
    "DJANGO_ROOT": "/var/django/sites"
    "STATIC": true

    # Websites / domains for these servers to host
    "websites": [
        {
            "name": "aasepia",
            "server_name": "aasepia.org",
            "sites": [
                {
                    "path": "/",
                    "project": "aasepia",
                }
            ]
        },
    ]
  roles:
    - { role: "python27", tags: ['python'] }
    - { role: "python36", tags: ['python'] }
    - { role: "postgresql-10-server", tags: ['postgresql']}
    - { role: "web_all_httpd_mod_wsgi", tags: ['python', 'httpd'] }
    - { role: "web_all_httpd_mod_wsgi_directories", tags: ['web'] }
    - { role: "web_all_httpd_mod_wsgi_conf", tags: ['web'] }
