---
- name: Install Apache httpd 2.4 from RHEL
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - httpd
    - mod_ssl

- name: Make sure httpd is started at boot.
  service:
    name: httpd
    enabled: true
    state: started

- name: Create apache user home directory
  file:
    name: "/home/apache/.ssh"
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: Create apache user authorized_keys
  copy:
    dest: "/home/apache/.ssh/authorized_keys"
    content: "",
    force: no
    owner: apache
    group: apache
    mode: 0600
