---
- name: Install Apache httpd 2.4 from RHEL
  yum:
    name: ['httpd', 'mod_ssl', 'python-certbot-apache']
    state: present

- name: Populate a conf file for ServerName
  copy:
    content: "ServerName {{ inventory_hostname }}"
    dest: /etc/httpd/conf.d/00-server-name.conf

- name: Make sure httpd is started at boot.
  service:
    name: httpd
    enabled: true

- name: Create a deployment user
  user:
    name: web_deploy
    comment: Account to deploy web sites.
    shell: /bin/bash
    group: apache
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Set authorized key from user's local public key file
  authorized_key:
    user: web_deploy
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
