---
- name: Install Apache httpd 2.4 from RHEL
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - httpd
    - mod_ssl

- name: Populate a conf file for ServerName
  copy:
    content: "ServerName {{ inventory_hostname }}"
    dest: /etc/httpd/conf.d/server-name.conf

- name: Make sure httpd is started at boot.
  service:
    name: httpd
    enabled: true
    state: started

- name: Create a deployment user
  user:
    name: django_deploy
    comment: Account to deploy Django sites.
    shell: /bin/bash
    group: apache
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Set authorized key from user's local public key file
  authorized_key:
    user: django_deploy
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
