---
- name: Install Apache httpd 2.4 from RHEL
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - httpd
    - mod_ssl

- name: Make sure httpd is started at boot.
  service:
    name: httpd
    enabled: true
    state: started

- name: Set authorized key from user's local public key file
  authorized_key:
    user: apache
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
