---
- name: Install MariaDB from EPEL
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - mariadb-server
    - mariadb-devel

- name: Make sure MariaDB is started at boot.
  service:
    name: mariadb
    state: started
    enabled: true
